### ISSUE TITLE
`Static.False()==true` throws `TypeError`

### ISSUE THREAD

**Issue by jlchan** [SciML/Static.jl#108]
In 1.8.5, `Static.False() == true` returns `false`. In v1.9, it throws a `TypeError`
```julia
julia> Static.False() == true
ERROR: TypeError: in typeassert, expected False, got a value of type True
Stacktrace:
 [1] convert
   @ ./number.jl:7 [inlined]
 [2] _promote
   @ ./promotion.jl:358 [inlined]
 [3] promote
   @ ./promotion.jl:381 [inlined]
 [4] ==(x::False, y::Bool)
   @ Base ./promotion.jl:449
 [5] top-level scope
   @ REPL[15]:1
```

**Comment by jlchan** [comment]
`Static.True() == false` throws a `TypeError` as well

**Comment by Tokazama** [comment]
It seems to be due to promotion

**Comment by Tokazama** [comment]
Looks like we need `Base.promote_rule(::Type{Bool}, T::Type{<:StaticNumber}) = promote_rule(Bool, eltype(T))` but it remains to be seen if it will cause invalidations.

**Comment by jlchan** [comment]
Added @Tokazama's promotion fix in https://github.com/SciML/Static.jl/pull/110. I need someone to approve workflows to check invalidations though.
