### ISSUE TITLE
Type promotion with Int32

### ISSUE THREAD

**Issue by YichengDWu** [SciML/Static.jl#111]
Is there a way to relax the type assertion without breaking anything to make the following return a `Int32`?
```julia
julia> static(1) +  Int32(1)
2

julia> typeof(ans)
Int64
```
Or
```julia
julia> static(Int32(1)) + Int32(1)
2

julia> typeof(ans)
Int64
```

**Comment by Tokazama** [comment]
Are you trying to pass the static info over to a GPU or some other device

**Comment by Tokazama** [comment]
> Yes, I'm trying to use Int32 index. Here maybe I should define something like StaticInt32?

There shouldn't be any runtime performance overhead from using something like `StaticFloat64` on GPU because it's conversion to `Float32` occurs at compile time. Similarly, your static index if written and compiled on a 64 bit machine shouldn't have trouble lowering to to `Int32` without any overhead. So creating new static types is typically just extra work for you and the compiler.

Messing with the way promotion works parallel to base might be a footgun, but we should ensure that this package is as helpful across devices as possible. Would you mind sharing a bit more code so that we can figure out a solution that is accessible to users and intuitive to developers?

**Comment by YichengDWu** [comment]
To be clear, the index is a dynamic `Int32`. My current code is already limited to Int types, so I can't share a MWE here. But here is an example, say I have a static-sized array of size `(static(3), static(4)`, and a dynamic index `(Int32(2), Int32(4))`, then the offset is computed as
```math
static(3) * Int32(2) + static(4) * Int32(4)=22  
```
I don't understand what you mean by "lowering to Int32`. Could you explain more?

**Comment by YichengDWu** [comment]
As far as I can tell, the index is promoted to `Int64`
```julia
julia> f(x,y) = static(3) * x + static(4) * y
f (generic function with 2 methods)

julia> @code_llvm f(Int32(2), Int32(2))
;  @ REPL[68]:1 within `f`
; Function Attrs: uwtable
define i64 @julia_f_2663(i32 signext %0, i32 signext %1) #0 {
top:
; ┌ @ promotion.jl:411 within `*` @ int.jl:1040
; │┌ @ int.jl:523 within `rem`
    %2 = sext i32 %0 to i64
; │└
; │ @ promotion.jl:411 within `*` @ int.jl:1042 @ int.jl:88
   %3 = mul nsw i64 %2, 3
; │ @ promotion.jl:411 within `*` @ int.jl:1040
; │┌ @ int.jl:523 within `rem`
    %4 = sext i32 %1 to i64
; │└
; │ @ promotion.jl:411 within `*` @ int.jl:1042 @ int.jl:88
   %5 = shl nsw i64 %4, 2
; └
; ┌ @ int.jl:87 within `+`
   %6 = add nsw i64 %5, %3
; └
  ret i64 %6
}
```

**Comment by Tokazama** [comment]
By "lowering" I mean it's lowered from a statically typed number to a dynamic variable. So `Int64(static(1))` and `Int32(static(1))` are both done at compile time and have no difference in runtime performance.

The point is that the theoretical use of `StaticInt32(3) * Int32(2) + StaticInt32(4) * Int32(4)` should have the same performance as `Int32(static(3)) * Int32(2) + Int32(static(4)) * Int32(4)`

**Comment by chriselrod** [comment]
I think @YichengDWu wants that to happen automatically, rather than the current situation, where the `Int32` promotes to `Int`.

**Comment by YichengDWu** [comment]
Ah, I know they won't make much difference in terms of calculation time. The primary reason for using Int32 indexing is to reduce register pressure on the GPU.

**Comment by Tokazama** [comment]
> I think @YichengDWu wants that to happen automatically, rather than the current situation, where the `Int32` promotes to `Int`.

But why would `StaticInt` be any different than `Int` which also requires explicit conversion to `Int32`?

**Comment by YichengDWu** [comment]
On the GPU, you can directly obtain a `UInt32` index, `threadIdx().x` (my apology, it's not the previously mentioned Int32).

**Comment by YichengDWu** [comment]
> I think @YichengDWu wants that to happen automatically, rather than the current situation, where the `Int32` promotes to `Int`.

Yes, changing the promote rule is the solution with the least code changes. I'm not sure if it would break other things.

**Comment by Tokazama** [comment]
> > I think @YichengDWu wants that to happen automatically, rather than the current situation, where the `Int32` promotes to `Int`.
> 
> Yes, changing the promote rule is the solution with the least code changes. I'm not sure if it would break other things.

Changing promotion rules smells like a footgun to me because it will change non GPU code despite clearly being intended only for GPU code. However, I'm never going to push back on a compelling argument where other Static.jl devs here strongly support it.

One way of knowing is just making a PR and we can see if it breaks downstream stuff.

**Comment by Tokazama** [comment]
> threadIdx().x

Perhaps we just need another tool like this for Static.jl

**Comment by YichengDWu** [comment]
Alright, let's see what would happen in #113.

**Comment by YichengDWu** [comment]
> Changing promotion rules smells like a footgun to me
Actually I agree. It's good enough for me to specialize at downstream. Thank you for your patience!
