### ISSUE TITLE
Unexpected interplay with complex numbers

### ISSUE THREAD

**Issue by lkdvos** [SciML/Static.jl#117]
When designing LinearAlgebra-like methods, often there is an optional scalar factor that by default is 0 or 1, for example: `mul(C, A, B, alpha, beta)` etc. In this context, it seemed like a good idea to use the static version to discern between the default cases and not. However, the following kind of threw me off:
```julia-repl
julia> NaN * false
0.0

julia> NaN * Zero
static(0)

julia> (NaN + 1im) * false
0.0+0.0im

julia> (NaN + 1im) * Zero
NaN+0.0im
```

Is there any reason for this, and if not, can I extend `Zero` to also work for complex numbers?

**Comment by Jutho** [comment]
This is another one:
```julia
julia> promote_type(Float64, typeof(static(0)))
Float64

julia> promote_type(ComplexF64, typeof(static(0)))
Number
```

Please don't make the same mistake as several old numerical libraries of having poor or broken complex support. Some areas of science do depend on complex numbers on a daily basis.

Should we start creating PRs for fixing these issues?

**Comment by Tokazama** [comment]
If a PR is made I'll review it and try to get input from one other person to make sure it doesn't break SciML packages.

**Comment by chriselrod** [comment]
I'm a little curious: why are people using `Static.jl`? SciML really wants to get away from it, and it is my fault that hasn't happened yet.
When I see issues like this, I think people are inadvertently moving in the wrong direction.

**Comment by Jutho** [comment]
Ok, I am not really following this ecosystem and so was unaware of this. Is the plan to move to something alternative, or just not to have any static values whatsoever?

Actually, all we use it for is a static zero and one value, for dealing with the default arguments in various BLAS-inspired functions within our tensor network ecosystem. (TensorOperations.jl, TensorKit.jl, MPSKit.jl, …), where then certain operations could be simplified by the compiler (multiplying by one, adding zero).

I thought that such a thing should exist centrally, and with all the invalidations discussions, that it would be wise to depend on a centrally maintained implementation thereof.

**Comment by chriselrod** [comment]
Personally, I think a `HardZero` type is hopefully fine (we don't want to preserve `NaN`s if overwriting an array in a BLAS op!!! I think that's also something to reasonably specialize on, as avoiding loading data is significant/it's materially different behavior that requires at least some different code generation).

I think the hard zero should go in a separate, lighter library.

The problem with a broad Static numbers is that people may use it in places where constant propagation would have worked.
It should only be used when you need to generate different code and dispatches, and people should think twice about when they really need that.
Using it for more than that, i.e. forcing compile time computation in the type system, is going to lead to the same sort of problems that `UnPack.jl` has with using overloadable dispatch on unpacking. See here for a discussion on (and deprecation of) `@unpack` in OrdinaryDiffEq:
https://github.com/SciML/OrdinaryDiffEq.jl/pull/1893

**Comment by Tokazama** [comment]
Sorry @chriselrod for the lack of help on my part here. Some academic snafus have completely consumed my time. If you need help cleaning up specific code related to this mess (that I helped create) feel free to ping me and I'll do my best to make time for it.

> Ok, I am not really following this ecosystem and so was unaware of this. Is the plan to move to something alternative, or just not to have any static values whatsoever?

There are a lot of uses for having support for static numbers but after a lot of discussion (probably over several years) I think this is an issue best solved within the Julia implementation. For example, iff Julia had native support for something like static fields or perhaps a better pointer/reference system that incorporated the concept of a compile time known value, then I think we could begin deprecating this package. Until then, this is the best tool for the job.

> Please don't make the same mistake as several old numerical libraries of having poor or broken complex support. Some areas of science do depend on complex numbers on a daily basis.

IIRC, @cscherrer has pointed out that complex numbers are a bit of a pain point even within Base Julia. `StaticFloat64` might be able to facilitate a better approach to this but I haven't given it much thought.

> I thought that such a thing should exist centrally, and with all the invalidations discussions, that it would be wise to depend on a centrally maintained implementation thereof.

It might be time to transition some of the raw numeric stuff to a different package where there is a vested interest in keeping this well-maintained for math in the long-run (if that is indeed of interest).

**Comment by cscherrer** [comment]
> I'm a little curious: why are people using `Static.jl`? SciML really wants to get away from it, and it is my fault that hasn't happened yet. When I see issues like this, I think people are inadvertently moving in the wrong direction.

For MeasureBase.jl @oschulz and I mostly need it so we can do things like
```julia
julia> d1 = productmeasure(fill(3.1 * Lebesgue(), 5))
ProductMeasure([3.1 * Lebesgue(ℝ), 3.1 * Lebesgue(ℝ), 3.1 * Lebesgue(ℝ), 3.1 * Lebesgue(ℝ), 3.1 * Lebesgue(ℝ)])

julia> d2 = productmeasure(fill(static(3.1) * Lebesgue(), 5))
286.3 * ProductMeasure([Lebesgue(ℝ), Lebesgue(ℝ), Lebesgue(ℝ), Lebesgue(ℝ), Lebesgue(ℝ)])
```

These are numerically the same, but for `d2` we know statically that the coefficients are all the same. Since `Base.issingletontype(typeof(d2))`, we can do computations without even needing to traverse the array. 

> IIRC, @cscherrer has pointed out that complex numbers are a bit of a pain point even within Base Julia. `StaticFloat64` might be able to facilitate a better approach to this but I haven't given it much thought.

Sorry @Tokazama , it might have been me but I don't remember that.

**Comment by oschulz** [comment]
Expanding a bit on the above: There are definitely use cases that require passing around static values, beyond what the compiler can infer from fixed values passed as parameters. Like @cscherrer wrote, one important example is dimensionality: In MeasureBase and other places we need to be able to express things like "this is a standard uniform distribution fixed to 2 dimensions. Based on that, rand will then generate a static instead of a dynamic array, for example (we're currently adding that), which can make a huge performance difference.

As for real numbers, static ones and zeros (especially) can also be very beneficial, for example to express that some log-abs-det-jacobian with always be zero and so on, resulting in compiler optimization of subsequent code.

The Julia compiler has gotten better at forwarding "constness" automatically, of course, but not to a point where "constness" is preserved when values are passed through longer calculations, stored in structs/tuples, etc.

**Comment by lkdvos** [comment]
So, my takeaway from this discussion is that this is probably not the package for us, and we just added the limited functionality we need from a hard `One` and `Zero` manually to [VectorInterface.jl](https://github.com/Jutho/VectorInterface.jl). While a stand-alone lightweight package that provides solely this functionality might be useful,  it seems that most users need a different niche subset of implemented methods based on the use-case.

In any case, thanks for explaining the current state-of-affairs, I was also not aware of the entire set of implications of most of these solutions.

I still feel like this package could benefit from a small amount of additional implemented methods that relate to complex numbers, mostly `Base.conj`, and an overload for `*` and `+` for the relevant `static(1)` and `static(0)`, but I think it is fair to close this issue and say that it is beyond your scope?

**Comment by oschulz** [comment]
> While a stand-alone lightweight package that provides solely this functionality might be useful,

There is Zeros.jl, but I don't know it (maintenance) status.
