### ISSUE TITLE
@aggressive_constprop -> @constprop renaming hasn't been backported to 1.7

### ISSUE THREAD

**Issue by stillyslalom** [SciML/Static.jl#17]
See https://github.com/JuliaLang/julia/pull/41781#issuecomment-916439343

Breaks downstream packages on 1.7 following https://github.com/SciML/Static.jl/commit/e3e240ca7ac04f06f799fc046ce259e685967353. Will need to more-carefully specify version bounds here: https://github.com/SciML/Static.jl/blob/e3e240ca7ac04f06f799fc046ce259e685967353/src/Static.jl#L9

**Comment by MasonProtter** [comment]
I got bit by this. Doing
```julia
]add Static@v0.3.1
```
solved the problem as a stopgap measure.

**Comment by ForceBru** [comment]
Same here:

```
Failed to precompile Symbolics [0c5d862f-8b57-4792-8d23-62f2024744c7] to /Users/forcebru/.julia/compiled/v1.7/Symbolics/jl_MDgUwq.
ERROR: LoadError: UndefVarError: @constprop not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/Static/cAyCC/src/Static.jl:10
 [2] include
   @ ./Base.jl:417 [inlined]
 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base ./loading.jl:1318
 [4] top-level scope
   @ none:1
 [5] eval
   @ ./boot.jl:373 [inlined]
 [6] eval(x::Expr)
   @ Base.MainInclude ./client.jl:453
 [7] top-level scope
   @ none:1
in expression starting at /Users/forcebru/.julia/packages/Static/cAyCC/src/Static.jl:1
```

Julia 1.7.0-beta3.0

**Comment by Tokazama** [comment]
This seems to be somewhat recent and possibly urgent, so I'll try to attend to any PRs addressing this. Unfortunately I want be at a computer to personally address it until tomorrow
