### ISSUE TITLE
Reference to undefined `to_index`

### ISSUE THREAD

**Issue by cscherrer** [SciML/Static.jl#42]
Just came across this, looks like `to_index` is defined in ArrayInterface:

https://github.com/SciML/Static.jl/blob/1566c585da6ce5aca8f795f3c0a39ffb7bbc666e/src/ndindex.jl#L150

**Comment by Tokazama** [comment]
This one is just a compatibility with `Base.to_indices`. so I forgot to import that.

**Comment by cscherrer** [comment]
Sorry, I don't understand. `to_index` is defined in ArrayInterface but used in Static, which does not have ArrayInterface as a dependency. I guess this needs to be refactored?

**Comment by Tokazama** [comment]
Should be fixed with #43. Thanks for bringing this to my attention.
